modLoader="javafml"
loaderVersion="[25,)" # (25 is current forge version)
issueTrackerURL="https://github.com/AlexApps99/yawns/issues"

[[mods]]
modId="yawnsmod"
displayName="YAWNS Mod"
version="${file.jarVersion}"

credits="Thanks to ForgeHax and Wurst for being there for me"
authors="@AlexApps#9295"

#updateJSONURL=""
displayURL="https://yawnsmod.github.io/"
logoFile="yawnsmod.png"

description='''
A free, open source hacked client with a focus on modularity, customization and automation.

Lol
'''

[[dependencies.yawnsmod]]
    modId="forge"
    mandatory=true
    versionRange="[25,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.yawnsmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.13.2]"
    ordering="NONE"
    side="BOTH"