name: Java CI
on:
  push:
    paths:
      - '**'
      - '!.github/**'
      - '!README.md'
      - '!.gitignore

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1
      with:
        submodules: recursive
        lfs: true
    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1.1.0
      with:
        java-version: 1.8 # Try to compile with both OpenJDK and Oracle JDK as a matrix
    
    - name: Build
      run: ./gradlew build
    
    - name: Upload artifacts to GitHub
      uses: actions/upload-artifact@v1
      continue-on-error: true
      with:
        name: YAWNS-Mod-JARs
        path: build/libs/
    
    - name: Upload artifacts to Discord
      continue-on-error: true
      run: >-
        curl
        -F 'payload_json={embeds:[{title:"${{github.repository}}@`${{github.sha}}`",url:"https://github.com/${{github.repository}}/commit/${{github.sha}}/checks/"}]}'
        -F "file=@$(build/libs/yawnsmod-?.?.jar)"
        -F 'content=@Developer'
        ${{secrets.BUILDS_WEBHOOK}}
