name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Setup Decompilation Workspace
      run: ./gradlew setupDecompWorkspace
    - name: Build
      run: ./gradlew build
    - uses: actions/upload-artifact@master
      with:
        name: 1.12.2 JAR file
        path: build/libs/yawnsmod-0.1.jar
