name: Java CI

on: [push]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1
      with:
        submodules: true
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8 # When setup-java gets updated remember to compile with OpenJDK too, as a matrix test
    - name: Build
      run: ./gradlew build
    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: YAWNS-Mod-JARs
        path: build/libs/
    - name: Post file to Discord
      run: |
        JARFILE=( build/libs/yawnsmod-?.?.jar )
        curl -X POST \
        -H 'Content-Type: multipart/form-data'  \
        -F 'payload_json={embeds:[{title:"YAWNS Mod Build",description:"A new build of YAWNS Mod is available to test!",url:"https://github.com/${{ github.repository }}/commit/${{ github.sha }}/checks/"}]}' \
        -F "file=@$JARFILE" \
        -F 'content=[${{ github.sha }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }}/)'
        ${{ secrets.BUILDS_WEBHOOK }}
